CREATE TABLE PERSONA(
    DNI VARCHAR2(9),
    NOMBRE VARCHAR2(30),
    AP1 VARCHAR2(50),
    AP2 VARCHAR2(50) NULL,
    TIPO CHAR(1),
    CONSTRAINT pk_persona PRIMARY KEY (DNI),
    -- RESTRICCION PARA EL DPMINIO DEL CAMPO TIPO-
    CONSTRAINT ck_tipo CHECK(TIPO IN ('A','S','B'))
);

CREATE TABLE BIBLIOTECARIO(
    DNIBIBLIOTECARIO VARCHAR2(9),
    CONSTRAINT pk_bibliotecario PRIMARY KEY (DNIBIBLIOTECARIO),
	CONSTRAINT fk_personabibliotecario FOREIGN KEY (DNIBIBLIOTECARIO) REFERENCES PERSONA(DNI)
);

CREATE TABLE SOCIO(
    DNISOCIO VARCHAR2(9),
    CONSTRAINT pk_socio PRIMARY KEY (DNISOCIO),
	CONSTRAINT fk_personasocio FOREIGN KEY (DNISOCIO) REFERENCES PERSONA(DNI)
);

CREATE TABLE AUTOR(
    DNIAUTOR VARCHAR2(9),
    CONSTRAINT pk_autor PRIMARY KEY (DNIAUTOR),
	CONSTRAINT fk_personaautor FOREIGN KEY (DNIAUTOR) REFERENCES PERSONA(DNI)
);

CREATE TABLE TEMATICA(
    TEMATICA VARCHAR2(30),
    CONSTRAINT pk_tematica PRIMARY KEY (TEMATICA),
);

CREATE TABLE LIBRO(
    ISBN NUMBER(13),
    TITULO VARCHAR2(30),
    NUMPAGINAS NUMBER(3),
    TEMATICA VARCHAR2(30),
    CONSTRAINT pk_libro PRIMARY KEY (ISBN),
	CONSTRAINT fk_tematicalibro FOREIGN KEY (TEMATICA) REFERENCES TEMATICA(TEMATICA)
);

CREATE TABLE LIBROAUTOR(
    ISBN NUMBER(13),
    DNI VARCHAR2(9),
    CONSTRAINT pk_libro PRIMARY KEY (ISBN, DNIAUTOR),
	CONSTRAINT fk_libro2 FOREIGN KEY (ISBN) REFERENCES LIBRO(ISBN),
    CONSTRAINT fk_libroautor2 FOREIGN KEY (DNIAUTOR) REFERENCES AUTOR(DNIAUTOR)
);

CREATE TABLE PRESTAMO(
    DNISOCIO VARCHAR2(9),
    DNIBIBLIOTECARIO VARCHAR2(9),
    ISBN NUMBER(13),
    CONSTRAINT pk_prestamo PRIMARY KEY (DNISOCIO, DNIBIBLIOTECARIO, ISBN),
	CONSTRAINT fk_dniprestamo FOREIGN KEY (DNISOCIO) REFERENCES PERSONA(DNISOCIO),
    CONSTRAINT fk_dniprestamo FOREIGN KEY (DNIBIBLIOTECARIO) REFERENCES PERSONA(DNIBIBLIOTECARIO),
    CONSTRAINT fk_libroprestamo FOREIGN KEY (ISBN) REFERENCES LIBRO(ISBN)
);