CREATE TABLE PROFESOR(
    DNI VARCHAR2(9),
    NOMBRE VARCHAR2(30),
    APELLIDO1 VARCHAR2(50),
    APELLIDO2 VARCHAR2(50) NULL,
    DIRECCION VARCHAR2(50),
    CUENTA NVARCHAR(26),
    TELEFONO NUMBER(9),
    CONSTRAINT pk_alumno PRIMARY KEY(DNI)
);

CREATE TABLE ASIGNATURA(
    CODASIG NUMBER(3),
    NOMBRE VARCHAR2(30),
    NUMHORAS NUMBER(3),
    CODCICLO NUMBER(3),
    CONSTRAINT pk_asignatura PRIMARY KEY(CODASIG),
    CONSTRAINT fk_asignatura FOREIGN KEY(DNI) REFERENCES PROFESOR(DNI),
    CONSTRAINT fk_asignatura FOREIGN KEY(CODCICLO) REFERENCES CICLOFORM(CODCICLO)
);

CREATE TABLE CICLOFORMATIVO(
    CODCICLO NUMBER(3),
    NOMBRE VARCHAR2(30),
    TIPO VARCHAR2(30),
    CONSTRAINT pk_cicloformativo PRIMARY KEY(CODCICLO)
);

CREATE TABLE IDIOMA(
    CODIDIOMA NUMBER(3),
    DESCRIPCION VARCHAR2(30),
    CONSTRAINT pk_idioma PRIMARY KEY(CODIDIOMA)
);

CREATE TABLE IDIOMASPROFESORES(
    CODIDIOMA NUMBER(3),
    DNI VARCHAR2(9),
    CONSTRAINT pk_idiomasprofesores PRIMARY KEY(CODIDIOMA,DNI),
    CONSTRAINT fk_idiomasprofesores FOREIGN KEY(CODIDIOMA) REFERENCES IDIOMA(CODIDIOMA),
    CONSTRAINT fk_dniprofesor FOREIGN KEY(DNI) REFERENCES PROFESOR(DNI)
);

CREATE TABLE ALUMNO(
    DNI VARCHAR2(9),
    NOMBRE VARCHAR2(30),
    APELLIDO1 VARCHAR2(50),
    APELLIDO2 VARCHAR2(50) NULL,
    DIRECCION VARCHAR2(50),
    TELEFONO NUMBER(9),
    CODIDIOMA NUMBER(9) NULL,
    CONSTRAINT pk_alumno PRIMARY KEY(DNI),
    CONSTRAINT fk_alumno FOREIGN KEY(CODIDIOMA) REFERENCES IDIOMA(CODIDIOMA)
);

CREATE TABLE MATRICULA(
    DNI VARCHAR2(9),
    CODASIG NUMBER(3),
    CONSTRAINT pk_matricula PRIMARY KEY(CODASIG,DNI),
    CONSTRAINT fk_dnialumno FOREIGN KEY(DNI) REFERENCES ALUMNO(DNI),
    CONSTRAINT fk_codasig FOREIGN KEY(CODASIG) REFERENCES ASIGNATURA(CODASIG)
);